# Site settings
title: ParaRec
description: 'ParaRec - a parallel recommendation system'
url: 'http://pavelkang.github.io/'
baseurl: '/418finalproject'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Kai Kang'
  email: sclingtt@gmail.com
  twitter_username: joshgerdes
  facebook_username: joshgerdes
  github_username:  pavelkang

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
